# 1. Numpy Intro

In [2]:
import numpy as np

In [3]:
np.random.seed(1337)

# 1.1 Basics of Matrices

In [9]:
x = np.array(
    [1, 4, 3]
)
x.shape

(3,)

In [7]:
y = np.array([[1, 4, 3],
              [9, 2, 7]])
y.shape


(2, 3)

In [10]:
z = np.array([[1, 4, 3]])   # What's the difference?


In [12]:
z.shape

(1, 3)

In [13]:
z = np.arange(1, 2000, 1)  # start, end, step
z[:10]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
z.shape

(1999,)

In [15]:
np.arange(0.5, 3, 0.5)


array([0.5, 1. , 1.5, 2. , 2.5])

In [16]:
np.arange(0.5, 10, 1).shape


(10,)

In [18]:
np.arange(0.5, 10, 1).reshape(5, 3).shape 


ValueError: cannot reshape array of size 10 into shape (5,3)

In [19]:
# Evenly spaced but we don't know the step
np.linspace(3, 9, 10)


array([3.        , 3.66666667, 4.33333333, 5.        , 5.66666667,
       6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])

In [20]:
print(x)
print(x[1])
print(x[1:])


[1 4 3]
4
[4 3]


In [21]:
np.zeros((3, 5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((5, 3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
a = np.arange(1, 7)
a


array([1, 2, 3, 4, 5, 6])

In [24]:
a.shape


(6,)

In [25]:
a[:3] = 1   # Assign to multiple locations
a


array([1, 1, 1, 4, 5, 6])

In [26]:
a[1:4] = [9, 8, 7]
a


array([1, 9, 8, 7, 5, 6])

In [27]:
# This is most useful
b = np.zeros((2, 2))
b[0, 0] = 1
b[0, 1] = 2
b[1, 1] = 4
b


array([[1., 2.],
       [0., 4.]])

In [28]:
b.shape


(2, 2)

In [29]:
print(b)


[[1. 2.]
 [0. 4.]]


In [30]:
b + 2


array([[3., 4.],
       [2., 6.]])

In [31]:
2 * b


array([[2., 4.],
       [0., 8.]])

In [32]:
b ** 2


array([[ 1.,  4.],
       [ 0., 16.]])

In [33]:
sum(b)


array([1., 6.])

In [34]:
b.sum()


7.0

In [35]:
b


array([[1., 2.],
       [0., 4.]])

In [37]:
b.sum(axis=0)


array([1., 6.])

In [38]:
b.sum(axis=1)

array([3., 4.])

In [39]:
b = np.array([[1, 2], [3, 4]])
d = np.array([[3, 4], [5, 6]])


In [40]:
print(b)
print(d)


[[1 2]
 [3 4]]
[[3 4]
 [5 6]]


In [41]:
b + d


array([[ 4,  6],
       [ 8, 10]])

In [42]:
b * d


array([[ 3,  8],
       [15, 24]])

In [43]:
b.dot(d)


array([[13, 16],
       [29, 36]])

In [44]:
b ** d


array([[   1,   16],
       [ 243, 4096]])